services:
  postgres:
    image: postgres:15
    container_name: user_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3243
      POSTGRES_DB: user-service
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: